### ISSUE TITLE
Branch 23-Duck-Details styles.css empty file

### ISSUE THREAD

**Issue by timiscoding** [ReactjsProgram/Redux-Immutable#1]
[app/components/DuckDetails/styles.css](https://github.com/ReactjsProgram/Redux-Immutable/blob/23-duck-details/app/components/DuckDetails/styles.css) is empty

I got the file from the next branch but it's probably a good idea to include it here as it corresponds to the video where you add these styles

**Comment by tylermcginnis** [comment]
Fixed. Thanks!
