### ISSUE TITLE
const Main = React.createClass not supported?

### ISSUE THREAD

**Issue by withoutwax** [ReactjsProgram/Redux-Immutable#15]
Hey Tyler! Thank you for awesome tutorial!
I was following around with your tutorials and hit the wall in the last minute:

Chrome Console:
```
VM1724 index_bundle.js:10076 Uncaught TypeError: _react2.default.createClass is not a function
    at Object.<anonymous> (VM1724 index_bundle.js:10076)
    at __webpack_require__ (VM1724 index_bundle.js:20)
    at Object.<anonymous> (VM1724 index_bundle.js:1164)
    at __webpack_require__ (VM1724 index_bundle.js:20)
    at module.exports (VM1724 index_bundle.js:63)
    at VM1724 index_bundle.js:66
```

I did few research and changed few of code into this:
```
npm install create-react-class --save-dev
```
```Javascript
import createReactClass from 'create-react-class'
```
```Javascript
const Main = createReactClass({
  render () {
    return (
      <p>Hello World!</p>
    )
  }
})
```

This worked!
So I was wondering whether the method in the tutorial is outdated...?

**Comment by jordan-realfoto** [comment]
@withoutwax `React.createClass` is now deprecated in favour of ES6 classes. Please see https://toddmotto.com/react-create-class-versus-component/

**Comment by withoutwax** [comment]
Thanks! I just decided to user the deprecated version for the sake of following the lectures 😄
