### ISSUE TITLE
Video does not match path to Oauth configuration

### ISSUE THREAD

**Issue by charlesjavelona** [ReactjsProgram/Redux-Immutable#3]
In the video showed at 1:47 to 1:54 seconds. 
Steps does not match the path to configure the Oauth configuration.

**Once in the dashboard, steps I took were**:
- _Click_ Add Product
- _Click_ Facebook Login
- _Scroll_ down to Client Oauth settings

**Comment by tylermcginnis** [comment]
Thanks for the heads up. Going to edit the video right now.
