### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by kstratis** [ReactjsProgram/Redux-Immutable#5]
After cloning the repo I `npm install` and `npm run start` to get this:

```
Module not found: Error: Cannot resolve module 'react-icons/lib/fa/reply'
```

Any clues? 

Thanks

**Comment by tylermcginnis** [comment]
For some reason 'react-icons/lib/fa/reply' was taken out of the Lib. Instead, use 'react-icons/lib/fa/mail-reply'. I've updated the curriculum to show this.
